// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class GDExtensionFFI {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GDExtensionFFI(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GDExtensionFFI.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void __va_start(
    ffi.Pointer<va_list> arg0,
  ) {
    return ___va_start(
      arg0,
    );
  }

  late final ___va_startPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<va_list>)>>(
          '__va_start');
  late final ___va_start =
      ___va_startPtr.asFunction<void Function(ffi.Pointer<va_list>)>();

  void __security_init_cookie() {
    return ___security_init_cookie();
  }

  late final ___security_init_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '__security_init_cookie');
  late final ___security_init_cookie =
      ___security_init_cookiePtr.asFunction<void Function()>();

  void __security_check_cookie(
    int _StackCookie,
  ) {
    return ___security_check_cookie(
      _StackCookie,
    );
  }

  late final ___security_check_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          '__security_check_cookie');
  late final ___security_check_cookie =
      ___security_check_cookiePtr.asFunction<void Function(int)>();

  void __report_gsfailure(
    int _StackCookie,
  ) {
    return ___report_gsfailure(
      _StackCookie,
    );
  }

  late final ___report_gsfailurePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          '__report_gsfailure');
  late final ___report_gsfailure =
      ___report_gsfailurePtr.asFunction<void Function(int)>();

  late final ffi.Pointer<ffi.UintPtr> ___security_cookie =
      _lookup<ffi.UintPtr>('__security_cookie');

  int get __security_cookie => ___security_cookie.value;

  set __security_cookie(int value) => ___security_cookie.value = value;

  void _invalid_parameter_noinfo() {
    return __invalid_parameter_noinfo();
  }

  late final __invalid_parameter_noinfoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '_invalid_parameter_noinfo');
  late final __invalid_parameter_noinfo =
      __invalid_parameter_noinfoPtr.asFunction<void Function()>();

  void _invalid_parameter_noinfo_noreturn() {
    return __invalid_parameter_noinfo_noreturn();
  }

  late final __invalid_parameter_noinfo_noreturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '_invalid_parameter_noinfo_noreturn');
  late final __invalid_parameter_noinfo_noreturn =
      __invalid_parameter_noinfo_noreturnPtr.asFunction<void Function()>();

  void _invoke_watson(
    ffi.Pointer<ffi.WChar> _Expression,
    ffi.Pointer<ffi.WChar> _FunctionName,
    ffi.Pointer<ffi.WChar> _FileName,
    int _LineNo,
    int _Reserved,
  ) {
    return __invoke_watson(
      _Expression,
      _FunctionName,
      _FileName,
      _LineNo,
      _Reserved,
    );
  }

  late final __invoke_watsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.WChar>,
              ffi.Pointer<ffi.WChar>,
              ffi.Pointer<ffi.WChar>,
              ffi.UnsignedInt,
              ffi.UintPtr)>>('_invoke_watson');
  late final __invoke_watson = __invoke_watsonPtr.asFunction<
      void Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>, int, int)>();

  ffi.Pointer<ffi.Int> _errno() {
    return __errno();
  }

  late final __errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int> Function()>>('_errno');
  late final __errno = __errnoPtr.asFunction<ffi.Pointer<ffi.Int> Function()>();

  int _set_errno(
    int _Value,
  ) {
    return __set_errno(
      _Value,
    );
  }

  late final __set_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Int)>>('_set_errno');
  late final __set_errno = __set_errnoPtr.asFunction<int Function(int)>();

  int _get_errno(
    ffi.Pointer<ffi.Int> _Value,
  ) {
    return __get_errno(
      _Value,
    );
  }

  late final __get_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Pointer<ffi.Int>)>>(
          '_get_errno');
  late final __get_errno =
      __get_errnoPtr.asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  int __threadid() {
    return ___threadid();
  }

  late final ___threadidPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedLong Function()>>('__threadid');
  late final ___threadid = ___threadidPtr.asFunction<int Function()>();

  int __threadhandle() {
    return ___threadhandle();
  }

  late final ___threadhandlePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function()>>('__threadhandle');
  late final ___threadhandle = ___threadhandlePtr.asFunction<int Function()>();

  void gde_init_c_interface(
    GDExtensionInterfaceGetProcAddress p_get_proc_address,
  ) {
    return _gde_init_c_interface(
      p_get_proc_address,
    );
  }

  late final _gde_init_c_interfacePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionInterfaceGetProcAddress)>>('gde_init_c_interface');
  late final _gde_init_c_interface = _gde_init_c_interfacePtr
      .asFunction<void Function(GDExtensionInterfaceGetProcAddress)>();

  void gde_get_library_path(
    GDExtensionClassLibraryPtr p_library,
    GDExtensionUninitializedStringPtr r_path,
  ) {
    return _gde_get_library_path(
      p_library,
      r_path,
    );
  }

  late final _gde_get_library_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionClassLibraryPtr,
              GDExtensionUninitializedStringPtr)>>('gde_get_library_path');
  late final _gde_get_library_path = _gde_get_library_pathPtr.asFunction<
      void Function(
          GDExtensionClassLibraryPtr, GDExtensionUninitializedStringPtr)>();

  void gde_print_error(
    ffi.Pointer<ffi.Char> p_description,
    ffi.Pointer<ffi.Char> p_function,
    ffi.Pointer<ffi.Char> p_file,
    int p_line,
    int p_editor_notify,
  ) {
    return _gde_print_error(
      p_description,
      p_function,
      p_file,
      p_line,
      p_editor_notify,
    );
  }

  late final _gde_print_errorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              GDExtensionBool)>>('gde_print_error');
  late final _gde_print_error = _gde_print_errorPtr.asFunction<
      void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, int, int)>();

  void gde_print_warning(
    ffi.Pointer<ffi.Char> p_description,
    ffi.Pointer<ffi.Char> p_function,
    ffi.Pointer<ffi.Char> p_file,
    int p_line,
    int p_editor_notify,
  ) {
    return _gde_print_warning(
      p_description,
      p_function,
      p_file,
      p_line,
      p_editor_notify,
    );
  }

  late final _gde_print_warningPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              GDExtensionBool)>>('gde_print_warning');
  late final _gde_print_warning = _gde_print_warningPtr.asFunction<
      void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, int, int)>();

  ffi.Pointer<ffi.Void> gde_mem_alloc(
    int p_bytes,
  ) {
    return _gde_mem_alloc(
      p_bytes,
    );
  }

  late final _gde_mem_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>(
          'gde_mem_alloc');
  late final _gde_mem_alloc =
      _gde_mem_allocPtr.asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  GDExtensionPtrConstructor gde_variant_get_ptr_constructor(
    int p_type,
    int p_constructor,
  ) {
    return _gde_variant_get_ptr_constructor(
      p_type,
      p_constructor,
    );
  }

  late final _gde_variant_get_ptr_constructorPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionPtrConstructor Function(
              ffi.Int32, ffi.Int32)>>('gde_variant_get_ptr_constructor');
  late final _gde_variant_get_ptr_constructor =
      _gde_variant_get_ptr_constructorPtr
          .asFunction<GDExtensionPtrConstructor Function(int, int)>();

  GDExtensionPtrDestructor gde_variant_get_ptr_destructor(
    int p_type,
  ) {
    return _gde_variant_get_ptr_destructor(
      p_type,
    );
  }

  late final _gde_variant_get_ptr_destructorPtr =
      _lookup<ffi.NativeFunction<GDExtensionPtrDestructor Function(ffi.Int32)>>(
          'gde_variant_get_ptr_destructor');
  late final _gde_variant_get_ptr_destructor =
      _gde_variant_get_ptr_destructorPtr
          .asFunction<GDExtensionPtrDestructor Function(int)>();

  void gde_variant_new_copy(
    GDExtensionUninitializedVariantPtr r_dest,
    GDExtensionConstVariantPtr p_src,
  ) {
    return _gde_variant_new_copy(
      r_dest,
      p_src,
    );
  }

  late final _gde_variant_new_copyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionUninitializedVariantPtr,
              GDExtensionConstVariantPtr)>>('gde_variant_new_copy');
  late final _gde_variant_new_copy = _gde_variant_new_copyPtr.asFunction<
      void Function(
          GDExtensionUninitializedVariantPtr, GDExtensionConstVariantPtr)>();

  void gde_variant_new_nil(
    GDExtensionUninitializedVariantPtr r_dest,
  ) {
    return _gde_variant_new_nil(
      r_dest,
    );
  }

  late final _gde_variant_new_nilPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionUninitializedVariantPtr)>>('gde_variant_new_nil');
  late final _gde_variant_new_nil = _gde_variant_new_nilPtr
      .asFunction<void Function(GDExtensionUninitializedVariantPtr)>();

  GDExtensionPtrBuiltInMethod gde_variant_get_ptr_builtin_method(
    int p_type,
    GDExtensionConstStringNamePtr p_method,
    int p_hash,
  ) {
    return _gde_variant_get_ptr_builtin_method(
      p_type,
      p_method,
      p_hash,
    );
  }

  late final _gde_variant_get_ptr_builtin_methodPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionPtrBuiltInMethod Function(
              ffi.Int32,
              GDExtensionConstStringNamePtr,
              GDExtensionInt)>>('gde_variant_get_ptr_builtin_method');
  late final _gde_variant_get_ptr_builtin_method =
      _gde_variant_get_ptr_builtin_methodPtr.asFunction<
          GDExtensionPtrBuiltInMethod Function(
              int, GDExtensionConstStringNamePtr, int)>();

  GDExtensionVariantFromTypeConstructorFunc
      gde_get_variant_from_type_constructor(
    int p_type,
  ) {
    return _gde_get_variant_from_type_constructor(
      p_type,
    );
  }

  late final _gde_get_variant_from_type_constructorPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionVariantFromTypeConstructorFunc Function(
              ffi.Int32)>>('gde_get_variant_from_type_constructor');
  late final _gde_get_variant_from_type_constructor =
      _gde_get_variant_from_type_constructorPtr.asFunction<
          GDExtensionVariantFromTypeConstructorFunc Function(int)>();

  GDExtensionTypeFromVariantConstructorFunc gde_get_variant_to_type_constructor(
    int p_type,
  ) {
    return _gde_get_variant_to_type_constructor(
      p_type,
    );
  }

  late final _gde_get_variant_to_type_constructorPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionTypeFromVariantConstructorFunc Function(
              ffi.Int32)>>('gde_get_variant_to_type_constructor');
  late final _gde_get_variant_to_type_constructor =
      _gde_get_variant_to_type_constructorPtr.asFunction<
          GDExtensionTypeFromVariantConstructorFunc Function(int)>();

  int gde_variant_get_type(
    GDExtensionConstVariantPtr p_self,
  ) {
    return _gde_variant_get_type(
      p_self,
    );
  }

  late final _gde_variant_get_typePtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(GDExtensionConstVariantPtr)>>(
      'gde_variant_get_type');
  late final _gde_variant_get_type = _gde_variant_get_typePtr
      .asFunction<int Function(GDExtensionConstVariantPtr)>();

  void gde_variant_call(
    GDExtensionVariantPtr p_self,
    GDExtensionConstStringNamePtr p_method,
    ffi.Pointer<GDExtensionConstVariantPtr> p_args,
    int p_argument_count,
    GDExtensionUninitializedVariantPtr r_return,
    ffi.Pointer<GDExtensionCallError> r_error,
  ) {
    return _gde_variant_call(
      p_self,
      p_method,
      p_args,
      p_argument_count,
      r_return,
      r_error,
    );
  }

  late final _gde_variant_callPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionVariantPtr,
              GDExtensionConstStringNamePtr,
              ffi.Pointer<GDExtensionConstVariantPtr>,
              GDExtensionInt,
              GDExtensionUninitializedVariantPtr,
              ffi.Pointer<GDExtensionCallError>)>>('gde_variant_call');
  late final _gde_variant_call = _gde_variant_callPtr.asFunction<
      void Function(
          GDExtensionVariantPtr,
          GDExtensionConstStringNamePtr,
          ffi.Pointer<GDExtensionConstVariantPtr>,
          int,
          GDExtensionUninitializedVariantPtr,
          ffi.Pointer<GDExtensionCallError>)>();

  GDExtensionPtrGetter gde_variant_get_ptr_getter(
    int p_type,
    GDExtensionConstStringNamePtr p_member,
  ) {
    return _gde_variant_get_ptr_getter(
      p_type,
      p_member,
    );
  }

  late final _gde_variant_get_ptr_getterPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionPtrGetter Function(ffi.Int32,
              GDExtensionConstStringNamePtr)>>('gde_variant_get_ptr_getter');
  late final _gde_variant_get_ptr_getter =
      _gde_variant_get_ptr_getterPtr.asFunction<
          GDExtensionPtrGetter Function(int, GDExtensionConstStringNamePtr)>();

  GDExtensionPtrSetter gde_variant_get_ptr_setter(
    int p_type,
    GDExtensionConstStringNamePtr p_member,
  ) {
    return _gde_variant_get_ptr_setter(
      p_type,
      p_member,
    );
  }

  late final _gde_variant_get_ptr_setterPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionPtrSetter Function(ffi.Int32,
              GDExtensionConstStringNamePtr)>>('gde_variant_get_ptr_setter');
  late final _gde_variant_get_ptr_setter =
      _gde_variant_get_ptr_setterPtr.asFunction<
          GDExtensionPtrSetter Function(int, GDExtensionConstStringNamePtr)>();

  GDExtensionPtrIndexedGetter gde_variant_get_ptr_indexed_getter(
    int p_type,
  ) {
    return _gde_variant_get_ptr_indexed_getter(
      p_type,
    );
  }

  late final _gde_variant_get_ptr_indexed_getterPtr = _lookup<
          ffi.NativeFunction<GDExtensionPtrIndexedGetter Function(ffi.Int32)>>(
      'gde_variant_get_ptr_indexed_getter');
  late final _gde_variant_get_ptr_indexed_getter =
      _gde_variant_get_ptr_indexed_getterPtr
          .asFunction<GDExtensionPtrIndexedGetter Function(int)>();

  GDExtensionPtrIndexedSetter gde_variant_get_ptr_indexed_setter(
    int p_type,
  ) {
    return _gde_variant_get_ptr_indexed_setter(
      p_type,
    );
  }

  late final _gde_variant_get_ptr_indexed_setterPtr = _lookup<
          ffi.NativeFunction<GDExtensionPtrIndexedSetter Function(ffi.Int32)>>(
      'gde_variant_get_ptr_indexed_setter');
  late final _gde_variant_get_ptr_indexed_setter =
      _gde_variant_get_ptr_indexed_setterPtr
          .asFunction<GDExtensionPtrIndexedSetter Function(int)>();

  GDExtensionPtrKeyedSetter gde_variant_get_ptr_keyed_setter(
    int p_type,
  ) {
    return _gde_variant_get_ptr_keyed_setter(
      p_type,
    );
  }

  late final _gde_variant_get_ptr_keyed_setterPtr = _lookup<
          ffi.NativeFunction<GDExtensionPtrKeyedSetter Function(ffi.Int32)>>(
      'gde_variant_get_ptr_keyed_setter');
  late final _gde_variant_get_ptr_keyed_setter =
      _gde_variant_get_ptr_keyed_setterPtr
          .asFunction<GDExtensionPtrKeyedSetter Function(int)>();

  GDExtensionPtrKeyedGetter gde_variant_get_ptr_keyed_getter(
    int p_type,
  ) {
    return _gde_variant_get_ptr_keyed_getter(
      p_type,
    );
  }

  late final _gde_variant_get_ptr_keyed_getterPtr = _lookup<
          ffi.NativeFunction<GDExtensionPtrKeyedGetter Function(ffi.Int32)>>(
      'gde_variant_get_ptr_keyed_getter');
  late final _gde_variant_get_ptr_keyed_getter =
      _gde_variant_get_ptr_keyed_getterPtr
          .asFunction<GDExtensionPtrKeyedGetter Function(int)>();

  GDExtensionPtrKeyedChecker gde_variant_get_ptr_keyed_checker(
    int p_type,
  ) {
    return _gde_variant_get_ptr_keyed_checker(
      p_type,
    );
  }

  late final _gde_variant_get_ptr_keyed_checkerPtr = _lookup<
          ffi.NativeFunction<GDExtensionPtrKeyedChecker Function(ffi.Int32)>>(
      'gde_variant_get_ptr_keyed_checker');
  late final _gde_variant_get_ptr_keyed_checker =
      _gde_variant_get_ptr_keyed_checkerPtr
          .asFunction<GDExtensionPtrKeyedChecker Function(int)>();

  void gde_variant_get_indexed(
    GDExtensionConstVariantPtr p_self,
    int p_index,
    GDExtensionUninitializedVariantPtr r_ret,
    ffi.Pointer<GDExtensionBool> r_valid,
    ffi.Pointer<GDExtensionBool> r_oob,
  ) {
    return _gde_variant_get_indexed(
      p_self,
      p_index,
      r_ret,
      r_valid,
      r_oob,
    );
  }

  late final _gde_variant_get_indexedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionConstVariantPtr,
              GDExtensionInt,
              GDExtensionUninitializedVariantPtr,
              ffi.Pointer<GDExtensionBool>,
              ffi.Pointer<GDExtensionBool>)>>('gde_variant_get_indexed');
  late final _gde_variant_get_indexed = _gde_variant_get_indexedPtr.asFunction<
      void Function(
          GDExtensionConstVariantPtr,
          int,
          GDExtensionUninitializedVariantPtr,
          ffi.Pointer<GDExtensionBool>,
          ffi.Pointer<GDExtensionBool>)>();

  void gde_variant_set_indexed(
    GDExtensionVariantPtr p_self,
    int p_index,
    GDExtensionConstVariantPtr p_value,
    ffi.Pointer<GDExtensionBool> r_valid,
    ffi.Pointer<GDExtensionBool> r_oob,
  ) {
    return _gde_variant_set_indexed(
      p_self,
      p_index,
      p_value,
      r_valid,
      r_oob,
    );
  }

  late final _gde_variant_set_indexedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionVariantPtr,
              GDExtensionInt,
              GDExtensionConstVariantPtr,
              ffi.Pointer<GDExtensionBool>,
              ffi.Pointer<GDExtensionBool>)>>('gde_variant_set_indexed');
  late final _gde_variant_set_indexed = _gde_variant_set_indexedPtr.asFunction<
      void Function(GDExtensionVariantPtr, int, GDExtensionConstVariantPtr,
          ffi.Pointer<GDExtensionBool>, ffi.Pointer<GDExtensionBool>)>();

  void gde_string_new_with_utf8_chars(
    GDExtensionUninitializedStringPtr r_dest,
    ffi.Pointer<ffi.Char> p_contents,
  ) {
    return _gde_string_new_with_utf8_chars(
      r_dest,
      p_contents,
    );
  }

  late final _gde_string_new_with_utf8_charsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionUninitializedStringPtr,
              ffi.Pointer<ffi.Char>)>>('gde_string_new_with_utf8_chars');
  late final _gde_string_new_with_utf8_chars =
      _gde_string_new_with_utf8_charsPtr.asFunction<
          void Function(
              GDExtensionUninitializedStringPtr, ffi.Pointer<ffi.Char>)>();

  int gde_string_to_utf8_chars(
    GDExtensionConstStringPtr p_self,
    ffi.Pointer<ffi.Char> r_text,
    int p_max_write_length,
  ) {
    return _gde_string_to_utf8_chars(
      p_self,
      r_text,
      p_max_write_length,
    );
  }

  late final _gde_string_to_utf8_charsPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionInt Function(
              GDExtensionConstStringPtr,
              ffi.Pointer<ffi.Char>,
              GDExtensionInt)>>('gde_string_to_utf8_chars');
  late final _gde_string_to_utf8_chars =
      _gde_string_to_utf8_charsPtr.asFunction<
          int Function(
              GDExtensionConstStringPtr, ffi.Pointer<ffi.Char>, int)>();

  int gde_string_to_utf16_chars(
    GDExtensionConstStringPtr p_self,
    ffi.Pointer<char16_t> r_text,
    int p_max_write_length,
  ) {
    return _gde_string_to_utf16_chars(
      p_self,
      r_text,
      p_max_write_length,
    );
  }

  late final _gde_string_to_utf16_charsPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionInt Function(
              GDExtensionConstStringPtr,
              ffi.Pointer<char16_t>,
              GDExtensionInt)>>('gde_string_to_utf16_chars');
  late final _gde_string_to_utf16_chars =
      _gde_string_to_utf16_charsPtr.asFunction<
          int Function(
              GDExtensionConstStringPtr, ffi.Pointer<char16_t>, int)>();

  GDExtensionObjectPtr gde_global_get_singleton(
    GDExtensionConstStringNamePtr p_name,
  ) {
    return _gde_global_get_singleton(
      p_name,
    );
  }

  late final _gde_global_get_singletonPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionObjectPtr Function(
              GDExtensionConstStringNamePtr)>>('gde_global_get_singleton');
  late final _gde_global_get_singleton =
      _gde_global_get_singletonPtr.asFunction<
          GDExtensionObjectPtr Function(GDExtensionConstStringNamePtr)>();

  ffi.Pointer<ffi.Void> gde_classdb_get_class_tag(
    GDExtensionConstStringNamePtr p_classname,
  ) {
    return _gde_classdb_get_class_tag(
      p_classname,
    );
  }

  late final _gde_classdb_get_class_tagPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
              GDExtensionConstStringNamePtr)>>('gde_classdb_get_class_tag');
  late final _gde_classdb_get_class_tag =
      _gde_classdb_get_class_tagPtr.asFunction<
          ffi.Pointer<ffi.Void> Function(GDExtensionConstStringNamePtr)>();

  void gde_classdb_register_extension_class(
    GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    GDExtensionConstStringNamePtr p_parent_class_name,
    ffi.Pointer<GDExtensionClassCreationInfo> p_extension_funcs,
  ) {
    return _gde_classdb_register_extension_class(
      p_library,
      p_class_name,
      p_parent_class_name,
      p_extension_funcs,
    );
  }

  late final _gde_classdb_register_extension_classPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringNamePtr,
                  ffi.Pointer<GDExtensionClassCreationInfo>)>>(
      'gde_classdb_register_extension_class');
  late final _gde_classdb_register_extension_class =
      _gde_classdb_register_extension_classPtr.asFunction<
          void Function(
              GDExtensionClassLibraryPtr,
              GDExtensionConstStringNamePtr,
              GDExtensionConstStringNamePtr,
              ffi.Pointer<GDExtensionClassCreationInfo>)>();

  void gde_classdb_register_extension_class_method(
    GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    ffi.Pointer<GDExtensionClassMethodInfo> p_method_info,
  ) {
    return _gde_classdb_register_extension_class_method(
      p_library,
      p_class_name,
      p_method_info,
    );
  }

  late final _gde_classdb_register_extension_class_methodPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  ffi.Pointer<GDExtensionClassMethodInfo>)>>(
      'gde_classdb_register_extension_class_method');
  late final _gde_classdb_register_extension_class_method =
      _gde_classdb_register_extension_class_methodPtr.asFunction<
          void Function(
              GDExtensionClassLibraryPtr,
              GDExtensionConstStringNamePtr,
              ffi.Pointer<GDExtensionClassMethodInfo>)>();

  void gde_classdb_register_extension_class_property(
    GDExtensionClassLibraryPtr p_library,
    GDExtensionConstStringNamePtr p_class_name,
    ffi.Pointer<GDExtensionPropertyInfo> p_info,
    GDExtensionConstStringNamePtr p_setter,
    GDExtensionConstStringNamePtr p_getter,
  ) {
    return _gde_classdb_register_extension_class_property(
      p_library,
      p_class_name,
      p_info,
      p_setter,
      p_getter,
    );
  }

  late final _gde_classdb_register_extension_class_propertyPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  ffi.Pointer<GDExtensionPropertyInfo>,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringNamePtr)>>(
      'gde_classdb_register_extension_class_property');
  late final _gde_classdb_register_extension_class_property =
      _gde_classdb_register_extension_class_propertyPtr.asFunction<
          void Function(
              GDExtensionClassLibraryPtr,
              GDExtensionConstStringNamePtr,
              ffi.Pointer<GDExtensionPropertyInfo>,
              GDExtensionConstStringNamePtr,
              GDExtensionConstStringNamePtr)>();

  GDExtensionMethodBindPtr gde_classdb_get_method_bind(
    GDExtensionConstStringNamePtr p_classname,
    GDExtensionConstStringNamePtr p_methodname,
    int p_hash,
  ) {
    return _gde_classdb_get_method_bind(
      p_classname,
      p_methodname,
      p_hash,
    );
  }

  late final _gde_classdb_get_method_bindPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionMethodBindPtr Function(
              GDExtensionConstStringNamePtr,
              GDExtensionConstStringNamePtr,
              GDExtensionInt)>>('gde_classdb_get_method_bind');
  late final _gde_classdb_get_method_bind =
      _gde_classdb_get_method_bindPtr.asFunction<
          GDExtensionMethodBindPtr Function(GDExtensionConstStringNamePtr,
              GDExtensionConstStringNamePtr, int)>();

  GDExtensionObjectPtr gde_classdb_construct_object(
    GDExtensionConstStringNamePtr p_classname,
  ) {
    return _gde_classdb_construct_object(
      p_classname,
    );
  }

  late final _gde_classdb_construct_objectPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionObjectPtr Function(
              GDExtensionConstStringNamePtr)>>('gde_classdb_construct_object');
  late final _gde_classdb_construct_object =
      _gde_classdb_construct_objectPtr.asFunction<
          GDExtensionObjectPtr Function(GDExtensionConstStringNamePtr)>();

  void gde_object_method_bind_call(
    GDExtensionMethodBindPtr p_method_bind,
    GDExtensionObjectPtr p_instance,
    ffi.Pointer<GDExtensionConstVariantPtr> p_args,
    int p_arg_count,
    GDExtensionUninitializedVariantPtr r_ret,
    ffi.Pointer<GDExtensionCallError> r_error,
  ) {
    return _gde_object_method_bind_call(
      p_method_bind,
      p_instance,
      p_args,
      p_arg_count,
      r_ret,
      r_error,
    );
  }

  late final _gde_object_method_bind_callPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionMethodBindPtr,
                  GDExtensionObjectPtr,
                  ffi.Pointer<GDExtensionConstVariantPtr>,
                  GDExtensionInt,
                  GDExtensionUninitializedVariantPtr,
                  ffi.Pointer<GDExtensionCallError>)>>(
      'gde_object_method_bind_call');
  late final _gde_object_method_bind_call =
      _gde_object_method_bind_callPtr.asFunction<
          void Function(
              GDExtensionMethodBindPtr,
              GDExtensionObjectPtr,
              ffi.Pointer<GDExtensionConstVariantPtr>,
              int,
              GDExtensionUninitializedVariantPtr,
              ffi.Pointer<GDExtensionCallError>)>();

  void gde_object_method_bind_ptrcall(
    GDExtensionMethodBindPtr p_method_bind,
    GDExtensionObjectPtr p_instance,
    ffi.Pointer<GDExtensionConstTypePtr> p_args,
    GDExtensionTypePtr r_ret,
  ) {
    return _gde_object_method_bind_ptrcall(
      p_method_bind,
      p_instance,
      p_args,
      r_ret,
    );
  }

  late final _gde_object_method_bind_ptrcallPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionMethodBindPtr,
              GDExtensionObjectPtr,
              ffi.Pointer<GDExtensionConstTypePtr>,
              GDExtensionTypePtr)>>('gde_object_method_bind_ptrcall');
  late final _gde_object_method_bind_ptrcall =
      _gde_object_method_bind_ptrcallPtr.asFunction<
          void Function(GDExtensionMethodBindPtr, GDExtensionObjectPtr,
              ffi.Pointer<GDExtensionConstTypePtr>, GDExtensionTypePtr)>();

  ffi.Pointer<ffi.Void> gde_object_get_instance_binding(
    GDExtensionObjectPtr p_o,
    ffi.Pointer<ffi.Void> p_token,
    ffi.Pointer<GDExtensionInstanceBindingCallbacks> p_callbacks,
  ) {
    return _gde_object_get_instance_binding(
      p_o,
      p_token,
      p_callbacks,
    );
  }

  late final _gde_object_get_instance_bindingPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                  GDExtensionObjectPtr,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<GDExtensionInstanceBindingCallbacks>)>>(
      'gde_object_get_instance_binding');
  late final _gde_object_get_instance_binding =
      _gde_object_get_instance_bindingPtr.asFunction<
          ffi.Pointer<ffi.Void> Function(
              GDExtensionObjectPtr,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<GDExtensionInstanceBindingCallbacks>)>();

  void gde_object_set_instance_binding(
    GDExtensionObjectPtr p_o,
    ffi.Pointer<ffi.Void> p_token,
    ffi.Pointer<ffi.Void> p_binding,
    ffi.Pointer<GDExtensionInstanceBindingCallbacks> p_callbacks,
  ) {
    return _gde_object_set_instance_binding(
      p_o,
      p_token,
      p_binding,
      p_callbacks,
    );
  }

  late final _gde_object_set_instance_bindingPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionObjectPtr,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<GDExtensionInstanceBindingCallbacks>)>>(
      'gde_object_set_instance_binding');
  late final _gde_object_set_instance_binding =
      _gde_object_set_instance_bindingPtr.asFunction<
          void Function(
              GDExtensionObjectPtr,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<GDExtensionInstanceBindingCallbacks>)>();

  void gde_object_set_instance(
    GDExtensionObjectPtr p_o,
    GDExtensionConstStringNamePtr p_classname,
    GDExtensionClassInstancePtr p_instance,
  ) {
    return _gde_object_set_instance(
      p_o,
      p_classname,
      p_instance,
    );
  }

  late final _gde_object_set_instancePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionObjectPtr, GDExtensionConstStringNamePtr,
              GDExtensionClassInstancePtr)>>('gde_object_set_instance');
  late final _gde_object_set_instance = _gde_object_set_instancePtr.asFunction<
      void Function(GDExtensionObjectPtr, GDExtensionConstStringNamePtr,
          GDExtensionClassInstancePtr)>();

  GDExtensionObjectPtr gde_object_cast_to(
    GDExtensionConstObjectPtr p_object,
    ffi.Pointer<ffi.Void> p_class_tag,
  ) {
    return _gde_object_cast_to(
      p_object,
      p_class_tag,
    );
  }

  late final _gde_object_cast_toPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionObjectPtr Function(GDExtensionConstObjectPtr,
              ffi.Pointer<ffi.Void>)>>('gde_object_cast_to');
  late final _gde_object_cast_to = _gde_object_cast_toPtr.asFunction<
      GDExtensionObjectPtr Function(
          GDExtensionConstObjectPtr, ffi.Pointer<ffi.Void>)>();

  void gde_object_destroy(
    GDExtensionObjectPtr p_o,
  ) {
    return _gde_object_destroy(
      p_o,
    );
  }

  late final _gde_object_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(GDExtensionObjectPtr)>>(
          'gde_object_destroy');
  late final _gde_object_destroy =
      _gde_object_destroyPtr.asFunction<void Function(GDExtensionObjectPtr)>();

  GDExtensionObjectPtr gde_ref_get_object(
    GDExtensionConstRefPtr p_ref,
  ) {
    return _gde_ref_get_object(
      p_ref,
    );
  }

  late final _gde_ref_get_objectPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionObjectPtr Function(
              GDExtensionConstRefPtr)>>('gde_ref_get_object');
  late final _gde_ref_get_object = _gde_ref_get_objectPtr
      .asFunction<GDExtensionObjectPtr Function(GDExtensionConstRefPtr)>();

  void gde_ref_set_object(
    GDExtensionRefPtr p_ref,
    GDExtensionObjectPtr p_object,
  ) {
    return _gde_ref_set_object(
      p_ref,
      p_object,
    );
  }

  late final _gde_ref_set_objectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionRefPtr, GDExtensionObjectPtr)>>('gde_ref_set_object');
  late final _gde_ref_set_object = _gde_ref_set_objectPtr
      .asFunction<void Function(GDExtensionRefPtr, GDExtensionObjectPtr)>();

  GDExtensionScriptInstancePtr gde_script_instance_create(
    ffi.Pointer<GDExtensionScriptInstanceInfo> p_info,
    GDExtensionScriptInstanceDataPtr p_instance_data,
  ) {
    return _gde_script_instance_create(
      p_info,
      p_instance_data,
    );
  }

  late final _gde_script_instance_createPtr = _lookup<
      ffi.NativeFunction<
          GDExtensionScriptInstancePtr Function(
              ffi.Pointer<GDExtensionScriptInstanceInfo>,
              GDExtensionScriptInstanceDataPtr)>>('gde_script_instance_create');
  late final _gde_script_instance_create =
      _gde_script_instance_createPtr.asFunction<
          GDExtensionScriptInstancePtr Function(
              ffi.Pointer<GDExtensionScriptInstanceInfo>,
              GDExtensionScriptInstanceDataPtr)>();

  GDExtensionScriptInstanceDataPtr gde_object_get_script_instance(
    GDExtensionConstObjectPtr p_object,
    GDExtensionObjectPtr p_language,
  ) {
    return _gde_object_get_script_instance(
      p_object,
      p_language,
    );
  }

  late final _gde_object_get_script_instancePtr = _lookup<
      ffi.NativeFunction<
          GDExtensionScriptInstanceDataPtr Function(GDExtensionConstObjectPtr,
              GDExtensionObjectPtr)>>('gde_object_get_script_instance');
  late final _gde_object_get_script_instance =
      _gde_object_get_script_instancePtr.asFunction<
          GDExtensionScriptInstanceDataPtr Function(
              GDExtensionConstObjectPtr, GDExtensionObjectPtr)>();
}

typedef va_list = ffi.Pointer<ffi.Char>;

class __crt_locale_data_public extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedShort> _locale_pctype;

  @ffi.Int()
  external int _locale_mb_cur_max;

  @ffi.UnsignedInt()
  external int _locale_lc_codepage;
}

class __crt_locale_pointers extends ffi.Struct {
  external ffi.Pointer<__crt_locale_data> locinfo;

  external ffi.Pointer<__crt_multibyte_data> mbcinfo;
}

class __crt_locale_data extends ffi.Opaque {}

class __crt_multibyte_data extends ffi.Opaque {}

class _Mbstatet extends ffi.Struct {
  @ffi.UnsignedLong()
  external int _Wchar;

  @ffi.UnsignedShort()
  external int _Byte;

  @ffi.UnsignedShort()
  external int _State;
}

typedef errno_t = ffi.Int;

abstract class GDExtensionVariantType {
  static const int GDEXTENSION_VARIANT_TYPE_NIL = 0;
  static const int GDEXTENSION_VARIANT_TYPE_BOOL = 1;
  static const int GDEXTENSION_VARIANT_TYPE_INT = 2;
  static const int GDEXTENSION_VARIANT_TYPE_FLOAT = 3;
  static const int GDEXTENSION_VARIANT_TYPE_STRING = 4;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR2 = 5;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR2I = 6;
  static const int GDEXTENSION_VARIANT_TYPE_RECT2 = 7;
  static const int GDEXTENSION_VARIANT_TYPE_RECT2I = 8;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR3 = 9;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR3I = 10;
  static const int GDEXTENSION_VARIANT_TYPE_TRANSFORM2D = 11;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR4 = 12;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR4I = 13;
  static const int GDEXTENSION_VARIANT_TYPE_PLANE = 14;
  static const int GDEXTENSION_VARIANT_TYPE_QUATERNION = 15;
  static const int GDEXTENSION_VARIANT_TYPE_AABB = 16;
  static const int GDEXTENSION_VARIANT_TYPE_BASIS = 17;
  static const int GDEXTENSION_VARIANT_TYPE_TRANSFORM3D = 18;
  static const int GDEXTENSION_VARIANT_TYPE_PROJECTION = 19;
  static const int GDEXTENSION_VARIANT_TYPE_COLOR = 20;
  static const int GDEXTENSION_VARIANT_TYPE_STRING_NAME = 21;
  static const int GDEXTENSION_VARIANT_TYPE_NODE_PATH = 22;
  static const int GDEXTENSION_VARIANT_TYPE_RID = 23;
  static const int GDEXTENSION_VARIANT_TYPE_OBJECT = 24;
  static const int GDEXTENSION_VARIANT_TYPE_CALLABLE = 25;
  static const int GDEXTENSION_VARIANT_TYPE_SIGNAL = 26;
  static const int GDEXTENSION_VARIANT_TYPE_DICTIONARY = 27;
  static const int GDEXTENSION_VARIANT_TYPE_ARRAY = 28;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY = 29;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY = 30;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY = 31;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY = 32;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY = 33;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY = 34;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY = 35;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY = 36;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY = 37;
  static const int GDEXTENSION_VARIANT_TYPE_VARIANT_MAX = 38;
}

abstract class GDExtensionVariantOperator {
  static const int GDEXTENSION_VARIANT_OP_EQUAL = 0;
  static const int GDEXTENSION_VARIANT_OP_NOT_EQUAL = 1;
  static const int GDEXTENSION_VARIANT_OP_LESS = 2;
  static const int GDEXTENSION_VARIANT_OP_LESS_EQUAL = 3;
  static const int GDEXTENSION_VARIANT_OP_GREATER = 4;
  static const int GDEXTENSION_VARIANT_OP_GREATER_EQUAL = 5;
  static const int GDEXTENSION_VARIANT_OP_ADD = 6;
  static const int GDEXTENSION_VARIANT_OP_SUBTRACT = 7;
  static const int GDEXTENSION_VARIANT_OP_MULTIPLY = 8;
  static const int GDEXTENSION_VARIANT_OP_DIVIDE = 9;
  static const int GDEXTENSION_VARIANT_OP_NEGATE = 10;
  static const int GDEXTENSION_VARIANT_OP_POSITIVE = 11;
  static const int GDEXTENSION_VARIANT_OP_MODULE = 12;
  static const int GDEXTENSION_VARIANT_OP_POWER = 13;
  static const int GDEXTENSION_VARIANT_OP_SHIFT_LEFT = 14;
  static const int GDEXTENSION_VARIANT_OP_SHIFT_RIGHT = 15;
  static const int GDEXTENSION_VARIANT_OP_BIT_AND = 16;
  static const int GDEXTENSION_VARIANT_OP_BIT_OR = 17;
  static const int GDEXTENSION_VARIANT_OP_BIT_XOR = 18;
  static const int GDEXTENSION_VARIANT_OP_BIT_NEGATE = 19;
  static const int GDEXTENSION_VARIANT_OP_AND = 20;
  static const int GDEXTENSION_VARIANT_OP_OR = 21;
  static const int GDEXTENSION_VARIANT_OP_XOR = 22;
  static const int GDEXTENSION_VARIANT_OP_NOT = 23;
  static const int GDEXTENSION_VARIANT_OP_IN = 24;
  static const int GDEXTENSION_VARIANT_OP_MAX = 25;
}

abstract class GDExtensionCallErrorType {
  static const int GDEXTENSION_CALL_OK = 0;
  static const int GDEXTENSION_CALL_ERROR_INVALID_METHOD = 1;
  static const int GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT = 2;
  static const int GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS = 3;
  static const int GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS = 4;
  static const int GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL = 5;
  static const int GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST = 6;
}

class GDExtensionCallError extends ffi.Struct {
  @ffi.Int32()
  external int error;

  @ffi.Int32()
  external int argument;

  @ffi.Int32()
  external int expected;
}

class GDExtensionInstanceBindingCallbacks extends ffi.Struct {
  external GDExtensionInstanceBindingCreateCallback create_callback;

  external GDExtensionInstanceBindingFreeCallback free_callback;

  external GDExtensionInstanceBindingReferenceCallback reference_callback;
}

typedef GDExtensionInstanceBindingCreateCallback = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionInstanceBindingFreeCallback = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionInstanceBindingReferenceCallback = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, GDExtensionBool)>>;
typedef GDExtensionBool = ffi.Uint8;

class GDExtensionPropertyInfo extends ffi.Struct {
  @ffi.Int32()
  external int type;

  external GDExtensionStringNamePtr name;

  external GDExtensionStringNamePtr class_name;

  @ffi.Uint32()
  external int hint;

  external GDExtensionStringPtr hint_string;

  @ffi.Uint32()
  external int usage;
}

typedef GDExtensionStringNamePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionStringPtr = ffi.Pointer<ffi.Void>;

class GDExtensionMethodInfo extends ffi.Struct {
  external GDExtensionStringNamePtr name;

  external GDExtensionPropertyInfo return_value;

  @ffi.Uint32()
  external int flags;

  @ffi.Int32()
  external int id;

  @ffi.Uint32()
  external int argument_count;

  external ffi.Pointer<GDExtensionPropertyInfo> arguments;

  @ffi.Uint32()
  external int default_argument_count;

  external ffi.Pointer<GDExtensionVariantPtr> default_arguments;
}

typedef GDExtensionVariantPtr = ffi.Pointer<ffi.Void>;

class GDExtensionClassCreationInfo extends ffi.Struct {
  @GDExtensionBool()
  external int is_virtual;

  @GDExtensionBool()
  external int is_abstract;

  external GDExtensionClassSet set_func;

  external GDExtensionClassGet get_func;

  external GDExtensionClassGetPropertyList get_property_list_func;

  external GDExtensionClassFreePropertyList free_property_list_func;

  external GDExtensionClassPropertyCanRevert property_can_revert_func;

  external GDExtensionClassPropertyGetRevert property_get_revert_func;

  external GDExtensionClassNotification notification_func;

  external GDExtensionClassToString to_string_func;

  external GDExtensionClassReference reference_func;

  external GDExtensionClassUnreference unreference_func;

  external GDExtensionClassCreateInstance create_instance_func;

  external GDExtensionClassFreeInstance free_instance_func;

  external GDExtensionClassGetVirtual get_virtual_func;

  external GDExtensionClassGetRID get_rid_func;

  external ffi.Pointer<ffi.Void> class_userdata;
}

typedef GDExtensionClassSet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionClassInstancePtr,
            GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr)>>;
typedef GDExtensionClassInstancePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionConstStringNamePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionConstVariantPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionClassGet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionClassInstancePtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionClassGetPropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<GDExtensionPropertyInfo> Function(
            GDExtensionClassInstancePtr, ffi.Pointer<ffi.Uint32>)>>;
typedef GDExtensionClassFreePropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionPropertyInfo>)>>;
typedef GDExtensionClassPropertyCanRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            GDExtensionClassInstancePtr, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionClassPropertyGetRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionClassInstancePtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionClassNotification = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr, ffi.Int32)>>;
typedef GDExtensionClassToString = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionBool>, GDExtensionStringPtr)>>;
typedef GDExtensionClassReference = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionClassInstancePtr)>>;
typedef GDExtensionClassUnreference = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionClassInstancePtr)>>;
typedef GDExtensionClassCreateInstance = ffi.Pointer<
    ffi.NativeFunction<GDExtensionObjectPtr Function(ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionObjectPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionClassFreeInstance = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void>, GDExtensionClassInstancePtr)>>;
typedef GDExtensionClassGetVirtual = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionClassCallVirtual Function(
            ffi.Pointer<ffi.Void>, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionClassCallVirtual = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionConstTypePtr>, GDExtensionTypePtr)>>;
typedef GDExtensionConstTypePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionTypePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionClassGetRID = ffi.Pointer<
    ffi.NativeFunction<ffi.Uint64 Function(GDExtensionClassInstancePtr)>>;

abstract class GDExtensionClassMethodFlags {
  static const int GDEXTENSION_METHOD_FLAG_NORMAL = 1;
  static const int GDEXTENSION_METHOD_FLAG_EDITOR = 2;
  static const int GDEXTENSION_METHOD_FLAG_CONST = 4;
  static const int GDEXTENSION_METHOD_FLAG_VIRTUAL = 8;
  static const int GDEXTENSION_METHOD_FLAG_VARARG = 16;
  static const int GDEXTENSION_METHOD_FLAG_STATIC = 32;
  static const int GDEXTENSION_METHOD_FLAGS_DEFAULT = 1;
}

abstract class GDExtensionClassMethodArgumentMetadata {
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE = 0;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8 = 1;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16 = 2;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32 = 3;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64 = 4;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8 = 5;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16 = 6;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32 = 7;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64 = 8;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT = 9;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE = 10;
}

class GDExtensionClassMethodInfo extends ffi.Struct {
  external GDExtensionStringNamePtr name;

  external ffi.Pointer<ffi.Void> method_userdata;

  external GDExtensionClassMethodCall call_func;

  external GDExtensionClassMethodPtrCall ptrcall_func;

  @ffi.Uint32()
  external int method_flags;

  @GDExtensionBool()
  external int has_return_value;

  external ffi.Pointer<GDExtensionPropertyInfo> return_value_info;

  @ffi.Int32()
  external int return_value_metadata;

  @ffi.Uint32()
  external int argument_count;

  external ffi.Pointer<GDExtensionPropertyInfo> arguments_info;

  external ffi.Pointer<ffi.Int32> arguments_metadata;

  @ffi.Uint32()
  external int default_argument_count;

  external ffi.Pointer<GDExtensionVariantPtr> default_arguments;
}

typedef GDExtensionClassMethodCall = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionConstVariantPtr>,
            GDExtensionInt,
            GDExtensionVariantPtr,
            ffi.Pointer<GDExtensionCallError>)>>;
typedef GDExtensionInt = ffi.Int64;
typedef GDExtensionClassMethodPtrCall = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void>, GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionConstTypePtr>, GDExtensionTypePtr)>>;

class GDExtensionScriptInstanceInfo extends ffi.Struct {
  external GDExtensionScriptInstanceSet set_func;

  external GDExtensionScriptInstanceGet get_func;

  external GDExtensionScriptInstanceGetPropertyList get_property_list_func;

  external GDExtensionScriptInstanceFreePropertyList free_property_list_func;

  external GDExtensionScriptInstancePropertyCanRevert property_can_revert_func;

  external GDExtensionScriptInstancePropertyGetRevert property_get_revert_func;

  external GDExtensionScriptInstanceGetOwner get_owner_func;

  external GDExtensionScriptInstanceGetPropertyState get_property_state_func;

  external GDExtensionScriptInstanceGetMethodList get_method_list_func;

  external GDExtensionScriptInstanceFreeMethodList free_method_list_func;

  external GDExtensionScriptInstanceGetPropertyType get_property_type_func;

  external GDExtensionScriptInstanceHasMethod has_method_func;

  external GDExtensionScriptInstanceCall call_func;

  external GDExtensionScriptInstanceNotification notification_func;

  external GDExtensionScriptInstanceToString to_string_func;

  external GDExtensionScriptInstanceRefCountIncremented
      refcount_incremented_func;

  external GDExtensionScriptInstanceRefCountDecremented
      refcount_decremented_func;

  external GDExtensionScriptInstanceGetScript get_script_func;

  external GDExtensionScriptInstanceIsPlaceholder is_placeholder_func;

  external GDExtensionScriptInstanceSet set_fallback_func;

  external GDExtensionScriptInstanceGet get_fallback_func;

  external GDExtensionScriptInstanceGetLanguage get_language_func;

  external GDExtensionScriptInstanceFree free_func;
}

typedef GDExtensionScriptInstanceSet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr)>>;
typedef GDExtensionScriptInstanceDataPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionScriptInstanceGet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionScriptInstanceGetPropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<GDExtensionPropertyInfo> Function(
            GDExtensionScriptInstanceDataPtr, ffi.Pointer<ffi.Uint32>)>>;
typedef GDExtensionScriptInstanceFreePropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            ffi.Pointer<GDExtensionPropertyInfo>)>>;
typedef GDExtensionScriptInstancePropertyCanRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionScriptInstancePropertyGetRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionScriptInstanceGetOwner = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionObjectPtr Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceGetPropertyState = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionScriptInstancePropertyStateAdd, ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionScriptInstancePropertyStateAdd = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionConstStringNamePtr,
            GDExtensionConstVariantPtr, ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionScriptInstanceGetMethodList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<GDExtensionMethodInfo> Function(
            GDExtensionScriptInstanceDataPtr, ffi.Pointer<ffi.Uint32>)>>;
typedef GDExtensionScriptInstanceFreeMethodList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            ffi.Pointer<GDExtensionMethodInfo>)>>;
typedef GDExtensionScriptInstanceGetPropertyType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Int32 Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, ffi.Pointer<GDExtensionBool>)>>;
typedef GDExtensionScriptInstanceHasMethod = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionScriptInstanceCall = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr,
            ffi.Pointer<GDExtensionConstVariantPtr>,
            GDExtensionInt,
            GDExtensionVariantPtr,
            ffi.Pointer<GDExtensionCallError>)>>;
typedef GDExtensionScriptInstanceNotification = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr, ffi.Int32)>>;
typedef GDExtensionScriptInstanceToString = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            ffi.Pointer<GDExtensionBool>, GDExtensionStringPtr)>>;
typedef GDExtensionScriptInstanceRefCountIncremented = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceRefCountDecremented = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceGetScript = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionObjectPtr Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceIsPlaceholder = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceGetLanguage = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionScriptLanguagePtr Function(
            GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptLanguagePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionScriptInstanceFree = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionScriptInstanceDataPtr)>>;

abstract class GDExtensionInitializationLevel {
  static const int GDEXTENSION_INITIALIZATION_CORE = 0;
  static const int GDEXTENSION_INITIALIZATION_SERVERS = 1;
  static const int GDEXTENSION_INITIALIZATION_SCENE = 2;
  static const int GDEXTENSION_INITIALIZATION_EDITOR = 3;
  static const int GDEXTENSION_MAX_INITIALIZATION_LEVEL = 4;
}

class GDExtensionInitialization extends ffi.Struct {
  @ffi.Int32()
  external int minimum_initialization_level;

  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)>> initialize;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)>> deinitialize;
}

class GDExtensionGodotVersion extends ffi.Struct {
  @ffi.Uint32()
  external int major;

  @ffi.Uint32()
  external int minor;

  @ffi.Uint32()
  external int patch;

  external ffi.Pointer<ffi.Char> string;
}

typedef GDExtensionInterfaceGetProcAddress = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionInterfaceFunctionPtr Function(ffi.Pointer<ffi.Char>)>>;
typedef GDExtensionInterfaceFunctionPtr
    = ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>;
typedef GDExtensionClassLibraryPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionUninitializedStringPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionPtrConstructor = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionUninitializedTypePtr,
            ffi.Pointer<GDExtensionConstTypePtr>)>>;
typedef GDExtensionUninitializedTypePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionPtrDestructor
    = ffi.Pointer<ffi.NativeFunction<ffi.Void Function(GDExtensionTypePtr)>>;
typedef GDExtensionUninitializedVariantPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionPtrBuiltInMethod = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionTypePtr,
            ffi.Pointer<GDExtensionConstTypePtr>,
            GDExtensionTypePtr,
            ffi.Int)>>;
typedef GDExtensionVariantFromTypeConstructorFunc = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionUninitializedVariantPtr, GDExtensionTypePtr)>>;
typedef GDExtensionTypeFromVariantConstructorFunc = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionUninitializedTypePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionPtrGetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionConstTypePtr, GDExtensionTypePtr)>>;
typedef GDExtensionPtrSetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionTypePtr, GDExtensionConstTypePtr)>>;
typedef GDExtensionPtrIndexedGetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionConstTypePtr, GDExtensionInt, GDExtensionTypePtr)>>;
typedef GDExtensionPtrIndexedSetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionTypePtr, GDExtensionInt, GDExtensionConstTypePtr)>>;
typedef GDExtensionPtrKeyedSetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionTypePtr, GDExtensionConstTypePtr,
            GDExtensionConstTypePtr)>>;
typedef GDExtensionPtrKeyedGetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionConstTypePtr, GDExtensionConstTypePtr,
            GDExtensionTypePtr)>>;
typedef GDExtensionPtrKeyedChecker = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Uint32 Function(
            GDExtensionConstVariantPtr, GDExtensionConstVariantPtr)>>;
typedef GDExtensionConstStringPtr = ffi.Pointer<ffi.Void>;
typedef char16_t = ffi.Uint16;
typedef GDExtensionMethodBindPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionConstObjectPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionConstRefPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionRefPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionScriptInstancePtr = ffi.Pointer<ffi.Void>;

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_NODISCARD = 1;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;
