import 'dart:ffi' as ffi;

import 'package:godot_dart/godot_dart.dart';

/// This file contains the FFI bindings to native functions defined in
/// godot_dart.dll. At the moment, these are not automatically generated by the
/// ffigen tool
class GodotDartNativeBindings {
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  GodotDartNativeBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  late final _setInstancePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionObjectPtr, GDExtensionConstStringNamePtr,
              ffi.Handle)>>('godot_dart_set_instance');
  late final _setInstance = _setInstancePtr.asFunction<
      void Function(
          GDExtensionObjectPtr, GDExtensionConstStringNamePtr, Object)>();

  void setInstance(
      GDExtensionObjectPtr gdOwner, StringName className, Object instance) {
    _setInstance(gdOwner, className.opaque.cast(), instance);
  }
}
