// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class GDExtensionFFI {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GDExtensionFFI(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GDExtensionFFI.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void __va_start(
    ffi.Pointer<va_list> arg0,
  ) {
    return ___va_start(
      arg0,
    );
  }

  late final ___va_startPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<va_list>)>>(
          '__va_start');
  late final ___va_start =
      ___va_startPtr.asFunction<void Function(ffi.Pointer<va_list>)>();

  void __security_init_cookie() {
    return ___security_init_cookie();
  }

  late final ___security_init_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '__security_init_cookie');
  late final ___security_init_cookie =
      ___security_init_cookiePtr.asFunction<void Function()>();

  void __security_check_cookie(
    int _StackCookie,
  ) {
    return ___security_check_cookie(
      _StackCookie,
    );
  }

  late final ___security_check_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          '__security_check_cookie');
  late final ___security_check_cookie =
      ___security_check_cookiePtr.asFunction<void Function(int)>();

  void __report_gsfailure(
    int _StackCookie,
  ) {
    return ___report_gsfailure(
      _StackCookie,
    );
  }

  late final ___report_gsfailurePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          '__report_gsfailure');
  late final ___report_gsfailure =
      ___report_gsfailurePtr.asFunction<void Function(int)>();

  late final ffi.Pointer<ffi.UintPtr> ___security_cookie =
      _lookup<ffi.UintPtr>('__security_cookie');

  int get __security_cookie => ___security_cookie.value;

  set __security_cookie(int value) => ___security_cookie.value = value;

  void _invalid_parameter_noinfo() {
    return __invalid_parameter_noinfo();
  }

  late final __invalid_parameter_noinfoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '_invalid_parameter_noinfo');
  late final __invalid_parameter_noinfo =
      __invalid_parameter_noinfoPtr.asFunction<void Function()>();

  void _invalid_parameter_noinfo_noreturn() {
    return __invalid_parameter_noinfo_noreturn();
  }

  late final __invalid_parameter_noinfo_noreturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '_invalid_parameter_noinfo_noreturn');
  late final __invalid_parameter_noinfo_noreturn =
      __invalid_parameter_noinfo_noreturnPtr.asFunction<void Function()>();

  void _invoke_watson(
    ffi.Pointer<ffi.WChar> _Expression,
    ffi.Pointer<ffi.WChar> _FunctionName,
    ffi.Pointer<ffi.WChar> _FileName,
    int _LineNo,
    int _Reserved,
  ) {
    return __invoke_watson(
      _Expression,
      _FunctionName,
      _FileName,
      _LineNo,
      _Reserved,
    );
  }

  late final __invoke_watsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.WChar>,
              ffi.Pointer<ffi.WChar>,
              ffi.Pointer<ffi.WChar>,
              ffi.UnsignedInt,
              ffi.UintPtr)>>('_invoke_watson');
  late final __invoke_watson = __invoke_watsonPtr.asFunction<
      void Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>, int, int)>();

  ffi.Pointer<ffi.Int> _errno() {
    return __errno();
  }

  late final __errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int> Function()>>('_errno');
  late final __errno = __errnoPtr.asFunction<ffi.Pointer<ffi.Int> Function()>();

  int _set_errno(
    int _Value,
  ) {
    return __set_errno(
      _Value,
    );
  }

  late final __set_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Int)>>('_set_errno');
  late final __set_errno = __set_errnoPtr.asFunction<int Function(int)>();

  int _get_errno(
    ffi.Pointer<ffi.Int> _Value,
  ) {
    return __get_errno(
      _Value,
    );
  }

  late final __get_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Pointer<ffi.Int>)>>(
          '_get_errno');
  late final __get_errno =
      __get_errnoPtr.asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  int __threadid() {
    return ___threadid();
  }

  late final ___threadidPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedLong Function()>>('__threadid');
  late final ___threadid = ___threadidPtr.asFunction<int Function()>();

  int __threadhandle() {
    return ___threadhandle();
  }

  late final ___threadhandlePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function()>>('__threadhandle');
  late final ___threadhandle = ___threadhandlePtr.asFunction<int Function()>();
}

typedef va_list = ffi.Pointer<ffi.Char>;

class __crt_locale_data_public extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedShort> _locale_pctype;

  @ffi.Int()
  external int _locale_mb_cur_max;

  @ffi.UnsignedInt()
  external int _locale_lc_codepage;
}

class __crt_locale_pointers extends ffi.Struct {
  external ffi.Pointer<__crt_locale_data> locinfo;

  external ffi.Pointer<__crt_multibyte_data> mbcinfo;
}

class __crt_locale_data extends ffi.Opaque {}

class __crt_multibyte_data extends ffi.Opaque {}

class _Mbstatet extends ffi.Struct {
  @ffi.UnsignedLong()
  external int _Wchar;

  @ffi.UnsignedShort()
  external int _Byte;

  @ffi.UnsignedShort()
  external int _State;
}

typedef errno_t = ffi.Int;

abstract class GDExtensionVariantType {
  static const int GDEXTENSION_VARIANT_TYPE_NIL = 0;
  static const int GDEXTENSION_VARIANT_TYPE_BOOL = 1;
  static const int GDEXTENSION_VARIANT_TYPE_INT = 2;
  static const int GDEXTENSION_VARIANT_TYPE_FLOAT = 3;
  static const int GDEXTENSION_VARIANT_TYPE_STRING = 4;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR2 = 5;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR2I = 6;
  static const int GDEXTENSION_VARIANT_TYPE_RECT2 = 7;
  static const int GDEXTENSION_VARIANT_TYPE_RECT2I = 8;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR3 = 9;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR3I = 10;
  static const int GDEXTENSION_VARIANT_TYPE_TRANSFORM2D = 11;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR4 = 12;
  static const int GDEXTENSION_VARIANT_TYPE_VECTOR4I = 13;
  static const int GDEXTENSION_VARIANT_TYPE_PLANE = 14;
  static const int GDEXTENSION_VARIANT_TYPE_QUATERNION = 15;
  static const int GDEXTENSION_VARIANT_TYPE_AABB = 16;
  static const int GDEXTENSION_VARIANT_TYPE_BASIS = 17;
  static const int GDEXTENSION_VARIANT_TYPE_TRANSFORM3D = 18;
  static const int GDEXTENSION_VARIANT_TYPE_PROJECTION = 19;
  static const int GDEXTENSION_VARIANT_TYPE_COLOR = 20;
  static const int GDEXTENSION_VARIANT_TYPE_STRING_NAME = 21;
  static const int GDEXTENSION_VARIANT_TYPE_NODE_PATH = 22;
  static const int GDEXTENSION_VARIANT_TYPE_RID = 23;
  static const int GDEXTENSION_VARIANT_TYPE_OBJECT = 24;
  static const int GDEXTENSION_VARIANT_TYPE_CALLABLE = 25;
  static const int GDEXTENSION_VARIANT_TYPE_SIGNAL = 26;
  static const int GDEXTENSION_VARIANT_TYPE_DICTIONARY = 27;
  static const int GDEXTENSION_VARIANT_TYPE_ARRAY = 28;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY = 29;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY = 30;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY = 31;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY = 32;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY = 33;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY = 34;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY = 35;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY = 36;
  static const int GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY = 37;
  static const int GDEXTENSION_VARIANT_TYPE_VARIANT_MAX = 38;
}

abstract class GDExtensionVariantOperator {
  static const int GDEXTENSION_VARIANT_OP_EQUAL = 0;
  static const int GDEXTENSION_VARIANT_OP_NOT_EQUAL = 1;
  static const int GDEXTENSION_VARIANT_OP_LESS = 2;
  static const int GDEXTENSION_VARIANT_OP_LESS_EQUAL = 3;
  static const int GDEXTENSION_VARIANT_OP_GREATER = 4;
  static const int GDEXTENSION_VARIANT_OP_GREATER_EQUAL = 5;
  static const int GDEXTENSION_VARIANT_OP_ADD = 6;
  static const int GDEXTENSION_VARIANT_OP_SUBTRACT = 7;
  static const int GDEXTENSION_VARIANT_OP_MULTIPLY = 8;
  static const int GDEXTENSION_VARIANT_OP_DIVIDE = 9;
  static const int GDEXTENSION_VARIANT_OP_NEGATE = 10;
  static const int GDEXTENSION_VARIANT_OP_POSITIVE = 11;
  static const int GDEXTENSION_VARIANT_OP_MODULE = 12;
  static const int GDEXTENSION_VARIANT_OP_POWER = 13;
  static const int GDEXTENSION_VARIANT_OP_SHIFT_LEFT = 14;
  static const int GDEXTENSION_VARIANT_OP_SHIFT_RIGHT = 15;
  static const int GDEXTENSION_VARIANT_OP_BIT_AND = 16;
  static const int GDEXTENSION_VARIANT_OP_BIT_OR = 17;
  static const int GDEXTENSION_VARIANT_OP_BIT_XOR = 18;
  static const int GDEXTENSION_VARIANT_OP_BIT_NEGATE = 19;
  static const int GDEXTENSION_VARIANT_OP_AND = 20;
  static const int GDEXTENSION_VARIANT_OP_OR = 21;
  static const int GDEXTENSION_VARIANT_OP_XOR = 22;
  static const int GDEXTENSION_VARIANT_OP_NOT = 23;
  static const int GDEXTENSION_VARIANT_OP_IN = 24;
  static const int GDEXTENSION_VARIANT_OP_MAX = 25;
}

abstract class GDExtensionCallErrorType {
  static const int GDEXTENSION_CALL_OK = 0;
  static const int GDEXTENSION_CALL_ERROR_INVALID_METHOD = 1;
  static const int GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT = 2;
  static const int GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS = 3;
  static const int GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS = 4;
  static const int GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL = 5;
  static const int GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST = 6;
}

class GDExtensionCallError extends ffi.Struct {
  @ffi.Int32()
  external int error;

  @ffi.Int32()
  external int argument;

  @ffi.Int32()
  external int expected;
}

class GDExtensionInstanceBindingCallbacks extends ffi.Struct {
  external GDExtensionInstanceBindingCreateCallback create_callback;

  external GDExtensionInstanceBindingFreeCallback free_callback;

  external GDExtensionInstanceBindingReferenceCallback reference_callback;
}

typedef GDExtensionInstanceBindingCreateCallback = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionInstanceBindingFreeCallback = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionInstanceBindingReferenceCallback = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, GDExtensionBool)>>;
typedef GDExtensionBool = ffi.Uint8;

class GDExtensionPropertyInfo extends ffi.Struct {
  @ffi.Int32()
  external int type;

  external GDExtensionStringNamePtr name;

  external GDExtensionStringNamePtr class_name;

  @ffi.Uint32()
  external int hint;

  external GDExtensionStringPtr hint_string;

  @ffi.Uint32()
  external int usage;
}

typedef GDExtensionStringNamePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionStringPtr = ffi.Pointer<ffi.Void>;

class GDExtensionMethodInfo extends ffi.Struct {
  external GDExtensionStringNamePtr name;

  external GDExtensionPropertyInfo return_value;

  @ffi.Uint32()
  external int flags;

  @ffi.Int32()
  external int id;

  @ffi.Uint32()
  external int argument_count;

  external ffi.Pointer<GDExtensionPropertyInfo> arguments;

  @ffi.Uint32()
  external int default_argument_count;

  external ffi.Pointer<GDExtensionVariantPtr> default_arguments;
}

typedef GDExtensionVariantPtr = ffi.Pointer<ffi.Void>;

class GDExtensionClassCreationInfo extends ffi.Struct {
  @GDExtensionBool()
  external int is_virtual;

  @GDExtensionBool()
  external int is_abstract;

  external GDExtensionClassSet set_func;

  external GDExtensionClassGet get_func;

  external GDExtensionClassGetPropertyList get_property_list_func;

  external GDExtensionClassFreePropertyList free_property_list_func;

  external GDExtensionClassPropertyCanRevert property_can_revert_func;

  external GDExtensionClassPropertyGetRevert property_get_revert_func;

  external GDExtensionClassNotification notification_func;

  external GDExtensionClassToString to_string_func;

  external GDExtensionClassReference reference_func;

  external GDExtensionClassUnreference unreference_func;

  external GDExtensionClassCreateInstance create_instance_func;

  external GDExtensionClassFreeInstance free_instance_func;

  external GDExtensionClassGetVirtual get_virtual_func;

  external GDExtensionClassGetRID get_rid_func;

  external ffi.Pointer<ffi.Void> class_userdata;
}

typedef GDExtensionClassSet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionClassInstancePtr,
            GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr)>>;
typedef GDExtensionClassInstancePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionConstStringNamePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionConstVariantPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionClassGet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionClassInstancePtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionClassGetPropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<GDExtensionPropertyInfo> Function(
            GDExtensionClassInstancePtr, ffi.Pointer<ffi.Uint32>)>>;
typedef GDExtensionClassFreePropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionPropertyInfo>)>>;
typedef GDExtensionClassPropertyCanRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            GDExtensionClassInstancePtr, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionClassPropertyGetRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionClassInstancePtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionClassNotification = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr, ffi.Int32)>>;
typedef GDExtensionClassToString = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionBool>, GDExtensionStringPtr)>>;
typedef GDExtensionClassReference = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionClassInstancePtr)>>;
typedef GDExtensionClassUnreference = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionClassInstancePtr)>>;
typedef GDExtensionClassCreateInstance = ffi.Pointer<
    ffi.NativeFunction<GDExtensionObjectPtr Function(ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionObjectPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionClassFreeInstance = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void>, GDExtensionClassInstancePtr)>>;
typedef GDExtensionClassGetVirtual = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionClassCallVirtual Function(
            ffi.Pointer<ffi.Void>, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionClassCallVirtual = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionConstTypePtr>, GDExtensionTypePtr)>>;
typedef GDExtensionConstTypePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionTypePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionClassGetRID = ffi.Pointer<
    ffi.NativeFunction<ffi.Uint64 Function(GDExtensionClassInstancePtr)>>;

abstract class GDExtensionClassMethodFlags {
  static const int GDEXTENSION_METHOD_FLAG_NORMAL = 1;
  static const int GDEXTENSION_METHOD_FLAG_EDITOR = 2;
  static const int GDEXTENSION_METHOD_FLAG_CONST = 4;
  static const int GDEXTENSION_METHOD_FLAG_VIRTUAL = 8;
  static const int GDEXTENSION_METHOD_FLAG_VARARG = 16;
  static const int GDEXTENSION_METHOD_FLAG_STATIC = 32;
  static const int GDEXTENSION_METHOD_FLAGS_DEFAULT = 1;
}

abstract class GDExtensionClassMethodArgumentMetadata {
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE = 0;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8 = 1;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16 = 2;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32 = 3;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64 = 4;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8 = 5;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16 = 6;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32 = 7;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64 = 8;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT = 9;
  static const int GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE = 10;
}

class GDExtensionClassMethodInfo extends ffi.Struct {
  external GDExtensionStringNamePtr name;

  external ffi.Pointer<ffi.Void> method_userdata;

  external GDExtensionClassMethodCall call_func;

  external GDExtensionClassMethodPtrCall ptrcall_func;

  @ffi.Uint32()
  external int method_flags;

  @GDExtensionBool()
  external int has_return_value;

  external ffi.Pointer<GDExtensionPropertyInfo> return_value_info;

  @ffi.Int32()
  external int return_value_metadata;

  @ffi.Uint32()
  external int argument_count;

  external ffi.Pointer<GDExtensionPropertyInfo> arguments_info;

  external ffi.Pointer<ffi.Int32> arguments_metadata;

  @ffi.Uint32()
  external int default_argument_count;

  external ffi.Pointer<GDExtensionVariantPtr> default_arguments;
}

typedef GDExtensionClassMethodCall = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionConstVariantPtr>,
            GDExtensionInt,
            GDExtensionVariantPtr,
            ffi.Pointer<GDExtensionCallError>)>>;
typedef GDExtensionInt = ffi.Int64;
typedef GDExtensionClassMethodPtrCall = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void>, GDExtensionClassInstancePtr,
            ffi.Pointer<GDExtensionConstTypePtr>, GDExtensionTypePtr)>>;

class GDExtensionScriptInstanceInfo extends ffi.Struct {
  external GDExtensionScriptInstanceSet set_func;

  external GDExtensionScriptInstanceGet get_func;

  external GDExtensionScriptInstanceGetPropertyList get_property_list_func;

  external GDExtensionScriptInstanceFreePropertyList free_property_list_func;

  external GDExtensionScriptInstancePropertyCanRevert property_can_revert_func;

  external GDExtensionScriptInstancePropertyGetRevert property_get_revert_func;

  external GDExtensionScriptInstanceGetOwner get_owner_func;

  external GDExtensionScriptInstanceGetPropertyState get_property_state_func;

  external GDExtensionScriptInstanceGetMethodList get_method_list_func;

  external GDExtensionScriptInstanceFreeMethodList free_method_list_func;

  external GDExtensionScriptInstanceGetPropertyType get_property_type_func;

  external GDExtensionScriptInstanceHasMethod has_method_func;

  external GDExtensionScriptInstanceCall call_func;

  external GDExtensionScriptInstanceNotification notification_func;

  external GDExtensionScriptInstanceToString to_string_func;

  external GDExtensionScriptInstanceRefCountIncremented
      refcount_incremented_func;

  external GDExtensionScriptInstanceRefCountDecremented
      refcount_decremented_func;

  external GDExtensionScriptInstanceGetScript get_script_func;

  external GDExtensionScriptInstanceIsPlaceholder is_placeholder_func;

  external GDExtensionScriptInstanceSet set_fallback_func;

  external GDExtensionScriptInstanceGet get_fallback_func;

  external GDExtensionScriptInstanceGetLanguage get_language_func;

  external GDExtensionScriptInstanceFree free_func;
}

typedef GDExtensionScriptInstanceSet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr)>>;
typedef GDExtensionScriptInstanceDataPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionScriptInstanceGet = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionScriptInstanceGetPropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<GDExtensionPropertyInfo> Function(
            GDExtensionScriptInstanceDataPtr, ffi.Pointer<ffi.Uint32>)>>;
typedef GDExtensionScriptInstanceFreePropertyList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            ffi.Pointer<GDExtensionPropertyInfo>)>>;
typedef GDExtensionScriptInstancePropertyCanRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionScriptInstancePropertyGetRevert = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionScriptInstanceGetOwner = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionObjectPtr Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceGetPropertyState = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionScriptInstancePropertyStateAdd, ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionScriptInstancePropertyStateAdd = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionConstStringNamePtr,
            GDExtensionConstVariantPtr, ffi.Pointer<ffi.Void>)>>;
typedef GDExtensionScriptInstanceGetMethodList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Pointer<GDExtensionMethodInfo> Function(
            GDExtensionScriptInstanceDataPtr, ffi.Pointer<ffi.Uint32>)>>;
typedef GDExtensionScriptInstanceFreeMethodList = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            ffi.Pointer<GDExtensionMethodInfo>)>>;
typedef GDExtensionScriptInstanceGetPropertyType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Int32 Function(GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr, ffi.Pointer<GDExtensionBool>)>>;
typedef GDExtensionScriptInstanceHasMethod = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(
            GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr)>>;
typedef GDExtensionScriptInstanceCall = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionScriptInstanceDataPtr,
            GDExtensionConstStringNamePtr,
            ffi.Pointer<GDExtensionConstVariantPtr>,
            GDExtensionInt,
            GDExtensionVariantPtr,
            ffi.Pointer<GDExtensionCallError>)>>;
typedef GDExtensionScriptInstanceNotification = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr, ffi.Int32)>>;
typedef GDExtensionScriptInstanceToString = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionScriptInstanceDataPtr,
            ffi.Pointer<GDExtensionBool>, GDExtensionStringPtr)>>;
typedef GDExtensionScriptInstanceRefCountIncremented = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceRefCountDecremented = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceGetScript = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionObjectPtr Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceIsPlaceholder = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionBool Function(GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptInstanceGetLanguage = ffi.Pointer<
    ffi.NativeFunction<
        GDExtensionScriptLanguagePtr Function(
            GDExtensionScriptInstanceDataPtr)>>;
typedef GDExtensionScriptLanguagePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionScriptInstanceFree = ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(GDExtensionScriptInstanceDataPtr)>>;

class GDExtensionInterface extends ffi.Struct {
  @ffi.Uint32()
  external int version_major;

  @ffi.Uint32()
  external int version_minor;

  @ffi.Uint32()
  external int version_patch;

  external ffi.Pointer<ffi.Char> version_string;

  external ffi
          .Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>
      mem_alloc;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)>>
      mem_realloc;

  external ffi
          .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      mem_free;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Int32, GDExtensionBool)>> print_error;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              GDExtensionBool)>> print_error_with_message;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              GDExtensionBool)>> print_warning;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              GDExtensionBool)>> print_warning_with_message;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              GDExtensionBool)>> print_script_error;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              GDExtensionBool)>> print_script_error_with_message;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Uint64 Function(GDExtensionConstStringNamePtr)>>
      get_native_struct_size;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionVariantPtr, GDExtensionConstVariantPtr)>>
      variant_new_copy;

  external ffi
          .Pointer<ffi.NativeFunction<ffi.Void Function(GDExtensionVariantPtr)>>
      variant_new_nil;

  external ffi
          .Pointer<ffi.NativeFunction<ffi.Void Function(GDExtensionVariantPtr)>>
      variant_destroy;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionVariantPtr,
              GDExtensionConstStringNamePtr,
              ffi.Pointer<GDExtensionConstVariantPtr>,
              GDExtensionInt,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionCallError>)>> variant_call;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int32,
              GDExtensionConstStringNamePtr,
              ffi.Pointer<GDExtensionConstVariantPtr>,
              GDExtensionInt,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionCallError>)>> variant_call_static;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int32,
              GDExtensionConstVariantPtr,
              GDExtensionConstVariantPtr,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_evaluate;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionVariantPtr,
              GDExtensionConstVariantPtr,
              GDExtensionConstVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_set;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionVariantPtr,
              GDExtensionConstStringNamePtr,
              GDExtensionConstVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_set_named;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionVariantPtr,
              GDExtensionConstVariantPtr,
              GDExtensionConstVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_set_keyed;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionVariantPtr,
              GDExtensionInt,
              GDExtensionConstVariantPtr,
              ffi.Pointer<GDExtensionBool>,
              ffi.Pointer<GDExtensionBool>)>> variant_set_indexed;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionConstVariantPtr,
              GDExtensionConstVariantPtr,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_get;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionConstVariantPtr,
              GDExtensionConstStringNamePtr,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_get_named;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionConstVariantPtr,
              GDExtensionConstVariantPtr,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_get_keyed;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionConstVariantPtr,
              GDExtensionInt,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>,
              ffi.Pointer<GDExtensionBool>)>> variant_get_indexed;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionBool Function(
              GDExtensionConstVariantPtr,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_iter_init;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionBool Function(
              GDExtensionConstVariantPtr,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_iter_next;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionConstVariantPtr,
              GDExtensionVariantPtr,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_iter_get;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionInt Function(GDExtensionConstVariantPtr)>> variant_hash;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionInt Function(
                  GDExtensionConstVariantPtr, GDExtensionInt)>>
      variant_recursive_hash;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionBool Function(
                  GDExtensionConstVariantPtr, GDExtensionConstVariantPtr)>>
      variant_hash_compare;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionBool Function(GDExtensionConstVariantPtr)>>
      variant_booleanize;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionConstVariantPtr, GDExtensionVariantPtr,
              GDExtensionBool)>> variant_duplicate;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionConstVariantPtr, GDExtensionStringPtr)>>
      variant_stringify;

  external ffi.Pointer<
          ffi.NativeFunction<ffi.Int32 Function(GDExtensionConstVariantPtr)>>
      variant_get_type;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionBool Function(
                  GDExtensionConstVariantPtr, GDExtensionConstStringNamePtr)>>
      variant_has_method;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionBool Function(
              ffi.Int32, GDExtensionConstStringNamePtr)>> variant_has_member;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionBool Function(
              GDExtensionConstVariantPtr,
              GDExtensionConstVariantPtr,
              ffi.Pointer<GDExtensionBool>)>> variant_has_key;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int32, GDExtensionStringPtr)>>
      variant_get_type_name;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionBool Function(ffi.Int32, ffi.Int32)>>
      variant_can_convert;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionBool Function(ffi.Int32, ffi.Int32)>>
      variant_can_convert_strict;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionVariantFromTypeConstructorFunc Function(ffi.Int32)>>
      get_variant_from_type_constructor;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionTypeFromVariantConstructorFunc Function(ffi.Int32)>>
      get_variant_to_type_constructor;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionPtrOperatorEvaluator Function(
                  ffi.Int32, ffi.Int32, ffi.Int32)>>
      variant_get_ptr_operator_evaluator;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionPtrBuiltInMethod Function(
                  ffi.Int32, GDExtensionConstStringNamePtr, GDExtensionInt)>>
      variant_get_ptr_builtin_method;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionPtrConstructor Function(ffi.Int32, ffi.Int32)>>
      variant_get_ptr_constructor;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionPtrDestructor Function(ffi.Int32)>>
      variant_get_ptr_destructor;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int32,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionConstVariantPtr>,
              ffi.Int32,
              ffi.Pointer<GDExtensionCallError>)>> variant_construct;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionPtrSetter Function(
                  ffi.Int32, GDExtensionConstStringNamePtr)>>
      variant_get_ptr_setter;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionPtrGetter Function(
                  ffi.Int32, GDExtensionConstStringNamePtr)>>
      variant_get_ptr_getter;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionPtrIndexedSetter Function(ffi.Int32)>>
      variant_get_ptr_indexed_setter;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionPtrIndexedGetter Function(ffi.Int32)>>
      variant_get_ptr_indexed_getter;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionPtrKeyedSetter Function(ffi.Int32)>>
      variant_get_ptr_keyed_setter;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionPtrKeyedGetter Function(ffi.Int32)>>
      variant_get_ptr_keyed_getter;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionPtrKeyedChecker Function(ffi.Int32)>>
      variant_get_ptr_keyed_checker;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int32, GDExtensionConstStringNamePtr,
              GDExtensionVariantPtr)>> variant_get_constant_value;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionPtrUtilityFunction Function(
                  GDExtensionConstStringNamePtr, GDExtensionInt)>>
      variant_get_ptr_utility_function;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<ffi.Char>)>>
      string_new_with_latin1_chars;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<ffi.Char>)>>
      string_new_with_utf8_chars;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<char16_t>)>>
      string_new_with_utf16_chars;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<char32_t>)>>
      string_new_with_utf32_chars;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<ffi.WChar>)>>
      string_new_with_wide_chars;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionStringPtr, ffi.Pointer<ffi.Char>, GDExtensionInt)>>
      string_new_with_latin1_chars_and_len;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionStringPtr, ffi.Pointer<ffi.Char>, GDExtensionInt)>>
      string_new_with_utf8_chars_and_len;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionStringPtr, ffi.Pointer<char16_t>, GDExtensionInt)>>
      string_new_with_utf16_chars_and_len;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionStringPtr, ffi.Pointer<char32_t>, GDExtensionInt)>>
      string_new_with_utf32_chars_and_len;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<ffi.WChar>,
              GDExtensionInt)>> string_new_with_wide_chars_and_len;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionInt Function(GDExtensionConstStringPtr,
              ffi.Pointer<ffi.Char>, GDExtensionInt)>> string_to_latin1_chars;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionInt Function(GDExtensionConstStringPtr,
              ffi.Pointer<ffi.Char>, GDExtensionInt)>> string_to_utf8_chars;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionInt Function(GDExtensionConstStringPtr,
              ffi.Pointer<char16_t>, GDExtensionInt)>> string_to_utf16_chars;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionInt Function(GDExtensionConstStringPtr,
              ffi.Pointer<char32_t>, GDExtensionInt)>> string_to_utf32_chars;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionInt Function(GDExtensionConstStringPtr,
              ffi.Pointer<ffi.WChar>, GDExtensionInt)>> string_to_wide_chars;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<char32_t> Function(
              GDExtensionStringPtr, GDExtensionInt)>> string_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<char32_t> Function(
                  GDExtensionConstStringPtr, GDExtensionInt)>>
      string_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionStringPtr, GDExtensionConstStringPtr)>>
      string_operator_plus_eq_string;

  external ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(GDExtensionStringPtr, char32_t)>>
      string_operator_plus_eq_char;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<ffi.Char>)>>
      string_operator_plus_eq_cstr;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<ffi.WChar>)>>
      string_operator_plus_eq_wcstr;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionStringPtr, ffi.Pointer<char32_t>)>>
      string_operator_plus_eq_c32str;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionInt Function(
                  GDExtensionObjectPtr, ffi.Pointer<ffi.Uint8>, ffi.Size)>>
      xml_parser_open_buffer;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionObjectPtr, ffi.Pointer<ffi.Uint8>, ffi.Uint64)>>
      file_access_store_buffer;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Uint64 Function(GDExtensionConstObjectPtr, ffi.Pointer<ffi.Uint8>,
              ffi.Uint64)>> file_access_get_buffer;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Int64 Function(
                  GDExtensionObjectPtr,
                  ffi.Pointer<
                      ffi.NativeFunction<
                          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32)>>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Int,
                  ffi.Int,
                  GDExtensionBool,
                  GDExtensionConstStringPtr)>>
      worker_thread_pool_add_native_group_task;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int64 Function(
              GDExtensionObjectPtr,
              ffi.Pointer<
                  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>,
              ffi.Pointer<ffi.Void>,
              GDExtensionBool,
              GDExtensionConstStringPtr)>> worker_thread_pool_add_native_task;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Uint8> Function(
                  GDExtensionTypePtr, GDExtensionInt)>>
      packed_byte_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Uint8> Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_byte_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionTypePtr Function(GDExtensionTypePtr, GDExtensionInt)>>
      packed_color_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionTypePtr Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_color_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Float> Function(
                  GDExtensionTypePtr, GDExtensionInt)>>
      packed_float32_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Float> Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_float32_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Double> Function(
                  GDExtensionTypePtr, GDExtensionInt)>>
      packed_float64_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Double> Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_float64_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Int32> Function(
                  GDExtensionTypePtr, GDExtensionInt)>>
      packed_int32_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Int32> Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_int32_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Int64> Function(
                  GDExtensionTypePtr, GDExtensionInt)>>
      packed_int64_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Int64> Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_int64_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionStringPtr Function(
                  GDExtensionTypePtr, GDExtensionInt)>>
      packed_string_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionStringPtr Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_string_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionTypePtr Function(GDExtensionTypePtr, GDExtensionInt)>>
      packed_vector2_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionTypePtr Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_vector2_array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionTypePtr Function(GDExtensionTypePtr, GDExtensionInt)>>
      packed_vector3_array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionTypePtr Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      packed_vector3_array_operator_index_const;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionVariantPtr Function(
              GDExtensionTypePtr, GDExtensionInt)>> array_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionVariantPtr Function(
                  GDExtensionConstTypePtr, GDExtensionInt)>>
      array_operator_index_const;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionTypePtr, GDExtensionConstTypePtr)>>
      array_ref;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionTypePtr,
              ffi.Int32,
              GDExtensionConstStringNamePtr,
              GDExtensionConstVariantPtr)>> array_set_typed;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionVariantPtr Function(
                  GDExtensionTypePtr, GDExtensionConstVariantPtr)>>
      dictionary_operator_index;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionVariantPtr Function(
                  GDExtensionConstTypePtr, GDExtensionConstVariantPtr)>>
      dictionary_operator_index_const;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionMethodBindPtr,
              GDExtensionObjectPtr,
              ffi.Pointer<GDExtensionConstVariantPtr>,
              GDExtensionInt,
              GDExtensionVariantPtr,
              ffi.Pointer<GDExtensionCallError>)>> object_method_bind_call;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionMethodBindPtr,
              GDExtensionObjectPtr,
              ffi.Pointer<GDExtensionConstTypePtr>,
              GDExtensionTypePtr)>> object_method_bind_ptrcall;

  external ffi
          .Pointer<ffi.NativeFunction<ffi.Void Function(GDExtensionObjectPtr)>>
      object_destroy;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionObjectPtr Function(GDExtensionConstStringNamePtr)>>
      global_get_singleton;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(
                  GDExtensionObjectPtr,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<GDExtensionInstanceBindingCallbacks>)>>
      object_get_instance_binding;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionObjectPtr,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<GDExtensionInstanceBindingCallbacks>)>>
      object_set_instance_binding;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(GDExtensionObjectPtr, GDExtensionConstStringNamePtr,
              GDExtensionClassInstancePtr)>> object_set_instance;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionObjectPtr Function(
                  GDExtensionConstObjectPtr, ffi.Pointer<ffi.Void>)>>
      object_cast_to;

  external ffi.Pointer<
          ffi.NativeFunction<GDExtensionObjectPtr Function(GDObjectInstanceID)>>
      object_get_instance_from_id;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDObjectInstanceID Function(GDExtensionConstObjectPtr)>>
      object_get_instance_id;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionObjectPtr Function(GDExtensionConstRefPtr)>>
      ref_get_object;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(GDExtensionRefPtr, GDExtensionObjectPtr)>>
      ref_set_object;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionScriptInstancePtr Function(
              ffi.Pointer<GDExtensionScriptInstanceInfo>,
              GDExtensionScriptInstanceDataPtr)>> script_instance_create;

  external ffi.Pointer<
          ffi.NativeFunction<
              GDExtensionObjectPtr Function(GDExtensionConstStringNamePtr)>>
      classdb_construct_object;

  external ffi.Pointer<
      ffi.NativeFunction<
          GDExtensionMethodBindPtr Function(
              GDExtensionConstStringNamePtr,
              GDExtensionConstStringNamePtr,
              GDExtensionInt)>> classdb_get_method_bind;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<ffi.Void> Function(GDExtensionConstStringNamePtr)>>
      classdb_get_class_tag;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringNamePtr,
                  ffi.Pointer<GDExtensionClassCreationInfo>)>>
      classdb_register_extension_class;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  ffi.Pointer<GDExtensionClassMethodInfo>)>>
      classdb_register_extension_class_method;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringNamePtr,
                  GDExtensionInt,
                  GDExtensionBool)>>
      classdb_register_extension_class_integer_constant;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  ffi.Pointer<GDExtensionPropertyInfo>,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringNamePtr)>>
      classdb_register_extension_class_property;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringPtr,
                  GDExtensionConstStringPtr)>>
      classdb_register_extension_class_property_group;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr,
                  GDExtensionConstStringNamePtr,
                  GDExtensionConstStringPtr,
                  GDExtensionConstStringPtr)>>
      classdb_register_extension_class_property_subgroup;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              GDExtensionClassLibraryPtr,
              GDExtensionConstStringNamePtr,
              GDExtensionConstStringNamePtr,
              ffi.Pointer<GDExtensionPropertyInfo>,
              GDExtensionInt)>> classdb_register_extension_class_signal;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr)>>
      classdb_unregister_extension_class;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  GDExtensionClassLibraryPtr, GDExtensionStringPtr)>>
      get_library_path;
}

typedef GDExtensionVariantFromTypeConstructorFunc = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionVariantPtr, GDExtensionTypePtr)>>;
typedef GDExtensionTypeFromVariantConstructorFunc = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionTypePtr, GDExtensionVariantPtr)>>;
typedef GDExtensionPtrOperatorEvaluator = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionConstTypePtr, GDExtensionConstTypePtr,
            GDExtensionTypePtr)>>;
typedef GDExtensionPtrBuiltInMethod = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionTypePtr,
            ffi.Pointer<GDExtensionConstTypePtr>,
            GDExtensionTypePtr,
            ffi.Int)>>;
typedef GDExtensionPtrConstructor = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionTypePtr, ffi.Pointer<GDExtensionConstTypePtr>)>>;
typedef GDExtensionPtrDestructor
    = ffi.Pointer<ffi.NativeFunction<ffi.Void Function(GDExtensionTypePtr)>>;
typedef GDExtensionPtrSetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionTypePtr, GDExtensionConstTypePtr)>>;
typedef GDExtensionPtrGetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionConstTypePtr, GDExtensionTypePtr)>>;
typedef GDExtensionPtrIndexedSetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionTypePtr, GDExtensionInt, GDExtensionConstTypePtr)>>;
typedef GDExtensionPtrIndexedGetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(
            GDExtensionConstTypePtr, GDExtensionInt, GDExtensionTypePtr)>>;
typedef GDExtensionPtrKeyedSetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionTypePtr, GDExtensionConstTypePtr,
            GDExtensionConstTypePtr)>>;
typedef GDExtensionPtrKeyedGetter = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionConstTypePtr, GDExtensionConstTypePtr,
            GDExtensionTypePtr)>>;
typedef GDExtensionPtrKeyedChecker = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Uint32 Function(
            GDExtensionConstVariantPtr, GDExtensionConstVariantPtr)>>;
typedef GDExtensionPtrUtilityFunction = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Void Function(GDExtensionTypePtr,
            ffi.Pointer<GDExtensionConstTypePtr>, ffi.Int)>>;
typedef char16_t = ffi.Uint16;
typedef char32_t = ffi.Uint32;
typedef GDExtensionConstStringPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionConstObjectPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionMethodBindPtr = ffi.Pointer<ffi.Void>;
typedef GDObjectInstanceID = ffi.Uint64;
typedef GDExtensionConstRefPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionRefPtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionScriptInstancePtr = ffi.Pointer<ffi.Void>;
typedef GDExtensionClassLibraryPtr = ffi.Pointer<ffi.Void>;

abstract class GDExtensionInitializationLevel {
  static const int GDEXTENSION_INITIALIZATION_CORE = 0;
  static const int GDEXTENSION_INITIALIZATION_SERVERS = 1;
  static const int GDEXTENSION_INITIALIZATION_SCENE = 2;
  static const int GDEXTENSION_INITIALIZATION_EDITOR = 3;
  static const int GDEXTENSION_MAX_INITIALIZATION_LEVEL = 4;
}

class GDExtensionInitialization extends ffi.Struct {
  @ffi.Int32()
  external int minimum_initialization_level;

  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)>> initialize;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int32)>> deinitialize;
}

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_NODISCARD = 1;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;
